paths_log_file_path: "./paths_log.csv"
process_log_file_path: "./process_log.csv"
grid_size: 4
path_min_length: 3
path_max_length: 5
path_prefix:
  - 1
path_suffix:
excluded_nodes:
  - 2
test_path:
  - 1
  - 7 
  - 8
  - 4
  - 9
attempt_delay: 10100
outputstrings:
  stdout_normal: >
    Attempting to decrypt data partition or user data via command line.
    Attempting to decrypt FBE for user 0...
    Failed to decrypt user 0
  stdout_success: Data successfully decrypted  
  stdout_error: some_error_string
adb_timeout: 30